//
//  TGCameraFlipButton.m
//  TGCameraViewController
//
//  Created by Fredrick Gabelmann on 11/3/15.
//  Copyright © 2015 Tudo Gostoso Internet. All rights reserved.
//

#import "TGCameraFlipButton.h"

@implementation TGCameraFlipButton

- (void)drawRect:(CGRect)frame
{
    //// Color Declarations
    UIColor* fillColor3 = self.foregroundColor;
    
    
    //// Subframes
    CGRect camflipwhiteGroup = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * -0.00000 - 0.5) + 1, CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.16250 + 0.5), floor(CGRectGetWidth(frame) * 1.00000 - 0.5) - floor(CGRectGetWidth(frame) * -0.00000 - 0.5), floor(CGRectGetHeight(frame) * 0.87083 + 0.5) - floor(CGRectGetHeight(frame) * 0.16250 + 0.5));
    
    
    //// cam-flip-white Group
    {
        //// Bezier Drawing
        UIBezierPath* bezierPath = [UIBezierPath bezierPath];
        [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.61420 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.00000 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.38582 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.00000 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.31154 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.05302 * CGRectGetHeight(camflipwhiteGroup)) controlPoint1: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.35591 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.00000 * CGRectGetHeight(camflipwhiteGroup)) controlPoint2: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.32812 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.01981 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.26298 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.15607 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.24813 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.16667 * CGRectGetHeight(camflipwhiteGroup)) controlPoint1: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.25968 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.16271 * CGRectGetHeight(camflipwhiteGroup)) controlPoint2: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.25413 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.16667 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.08929 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.16667 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.00000 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.28571 * CGRectGetHeight(camflipwhiteGroup)) controlPoint1: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.04007 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.16667 * CGRectGetHeight(camflipwhiteGroup)) controlPoint2: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.00000 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.22007 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.00000 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.88095 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.08929 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 1.00000 * CGRectGetHeight(camflipwhiteGroup)) controlPoint1: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.00000 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.94660 * CGRectGetHeight(camflipwhiteGroup)) controlPoint2: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.04007 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 1.00000 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.91071 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 1.00000 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 1.00000 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.88095 * CGRectGetHeight(camflipwhiteGroup)) controlPoint1: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.95995 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 1.00000 * CGRectGetHeight(camflipwhiteGroup)) controlPoint2: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 1.00000 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.94660 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 1.00000 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.28571 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.91071 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.16667 * CGRectGetHeight(camflipwhiteGroup)) controlPoint1: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 1.00000 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.22007 * CGRectGetHeight(camflipwhiteGroup)) controlPoint2: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.95995 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.16667 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.75189 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.16667 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.73704 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.15607 * CGRectGetHeight(camflipwhiteGroup)) controlPoint1: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.74591 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.16667 * CGRectGetHeight(camflipwhiteGroup)) controlPoint2: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.74036 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.16271 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.68848 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.05302 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.61420 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.00000 * CGRectGetHeight(camflipwhiteGroup)) controlPoint1: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.67189 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.01981 * CGRectGetHeight(camflipwhiteGroup)) controlPoint2: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.64412 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.00000 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath closePath];
        [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.61420 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.04762 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.65877 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.07943 * CGRectGetHeight(camflipwhiteGroup)) controlPoint1: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.63211 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.04762 * CGRectGetHeight(camflipwhiteGroup)) controlPoint2: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.64884 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.05955 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.70730 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.18248 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.75189 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.21429 * CGRectGetHeight(camflipwhiteGroup)) controlPoint1: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.71725 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.20236 * CGRectGetHeight(camflipwhiteGroup)) controlPoint2: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.73398 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.21429 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.91071 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.21429 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.96429 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.28571 * CGRectGetHeight(camflipwhiteGroup)) controlPoint1: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.94030 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.21429 * CGRectGetHeight(camflipwhiteGroup)) controlPoint2: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.96429 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.24626 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.96429 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.88095 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.91071 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.95238 * CGRectGetHeight(camflipwhiteGroup)) controlPoint1: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.96429 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.92040 * CGRectGetHeight(camflipwhiteGroup)) controlPoint2: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.94030 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.95238 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.08929 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.95238 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.03571 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.88095 * CGRectGetHeight(camflipwhiteGroup)) controlPoint1: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.05971 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.95238 * CGRectGetHeight(camflipwhiteGroup)) controlPoint2: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.03571 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.92040 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.03571 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.28571 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.08929 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.21429 * CGRectGetHeight(camflipwhiteGroup)) controlPoint1: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.03571 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.24626 * CGRectGetHeight(camflipwhiteGroup)) controlPoint2: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.05971 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.21429 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.24813 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.21429 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.29270 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.18248 * CGRectGetHeight(camflipwhiteGroup)) controlPoint1: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.26605 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.21429 * CGRectGetHeight(camflipwhiteGroup)) controlPoint2: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.28277 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.20236 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.34125 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.07943 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.38582 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.04762 * CGRectGetHeight(camflipwhiteGroup)) controlPoint1: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.35118 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.05955 * CGRectGetHeight(camflipwhiteGroup)) controlPoint2: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.36791 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.04762 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.61420 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.04762 * CGRectGetHeight(camflipwhiteGroup))];
        [bezierPath closePath];
        [fillColor3 setFill];
        [bezierPath fill];
        
        
        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = [UIBezierPath bezierPath];
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.73170 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.52381 * CGRectGetHeight(camflipwhiteGroup))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.50893 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.23810 * CGRectGetHeight(camflipwhiteGroup)) controlPoint1: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.72699 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.36500 * CGRectGetHeight(camflipwhiteGroup)) controlPoint2: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.62920 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.23810 * CGRectGetHeight(camflipwhiteGroup))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.35772 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.31724 * CGRectGetHeight(camflipwhiteGroup)) controlPoint1: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.45052 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.23810 * CGRectGetHeight(camflipwhiteGroup)) controlPoint2: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.39750 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.26826 * CGRectGetHeight(camflipwhiteGroup))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.39565 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.36783 * CGRectGetHeight(camflipwhiteGroup))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.50893 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.30952 * CGRectGetHeight(camflipwhiteGroup)) controlPoint1: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.42572 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.33171 * CGRectGetHeight(camflipwhiteGroup)) controlPoint2: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.46538 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.30952 * CGRectGetHeight(camflipwhiteGroup))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.67813 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.52381 * CGRectGetHeight(camflipwhiteGroup)) controlPoint1: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.59947 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.30952 * CGRectGetHeight(camflipwhiteGroup)) controlPoint2: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.67343 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.40464 * CGRectGetHeight(camflipwhiteGroup))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.61608 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.52381 * CGRectGetHeight(camflipwhiteGroup))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.70536 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.67262 * CGRectGetHeight(camflipwhiteGroup))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.79465 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.52381 * CGRectGetHeight(camflipwhiteGroup))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.73170 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.52381 * CGRectGetHeight(camflipwhiteGroup))];
        [bezier2Path closePath];
        [fillColor3 setFill];
        [bezier2Path fill];
        
        
        //// Bezier 3 Drawing
        UIBezierPath* bezier3Path = [UIBezierPath bezierPath];
        [bezier3Path moveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.50894 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.76190 * CGRectGetHeight(camflipwhiteGroup))];
        [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.34021 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.55357 * CGRectGetHeight(camflipwhiteGroup)) controlPoint1: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.41994 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.76190 * CGRectGetHeight(camflipwhiteGroup)) controlPoint2: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.34710 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.66990 * CGRectGetHeight(camflipwhiteGroup))];
        [bezier3Path addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.40179 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.55357 * CGRectGetHeight(camflipwhiteGroup))];
        [bezier3Path addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.31251 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.40476 * CGRectGetHeight(camflipwhiteGroup))];
        [bezier3Path addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.22322 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.55357 * CGRectGetHeight(camflipwhiteGroup))];
        [bezier3Path addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.28656 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.55357 * CGRectGetHeight(camflipwhiteGroup))];
        [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.50894 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.83333 * CGRectGetHeight(camflipwhiteGroup)) controlPoint1: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.29354 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.70955 * CGRectGetHeight(camflipwhiteGroup)) controlPoint2: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.39021 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.83333 * CGRectGetHeight(camflipwhiteGroup))];
        [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.66015 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.75419 * CGRectGetHeight(camflipwhiteGroup)) controlPoint1: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.56737 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.83333 * CGRectGetHeight(camflipwhiteGroup)) controlPoint2: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.62037 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.80317 * CGRectGetHeight(camflipwhiteGroup))];
        [bezier3Path addLineToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.62222 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.70360 * CGRectGetHeight(camflipwhiteGroup))];
        [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.50894 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.76190 * CGRectGetHeight(camflipwhiteGroup)) controlPoint1: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.59215 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.73971 * CGRectGetHeight(camflipwhiteGroup)) controlPoint2: CGPointMake(CGRectGetMinX(camflipwhiteGroup) + 0.55251 * CGRectGetWidth(camflipwhiteGroup), CGRectGetMinY(camflipwhiteGroup) + 0.76190 * CGRectGetHeight(camflipwhiteGroup))];
        [bezier3Path closePath];
        [fillColor3 setFill];
        [bezier3Path fill];
    }
}

@end
